// <auto-generated />
using System;
using AdoteAquiAppWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdoteAquiAppWeb.Data.Migrations
{
    [DbContext(typeof(AdoteAquiDbContext))]
    [Migration("20231205011912_AddDataBreedInit")]
    partial class AddDataBreedInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("AdoteAquiAppWeb.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Adoption")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Andress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BreedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.ToTable("TBL_ANIMAL");
                });

            modelBuilder.Entity("AdoteAquiAppWeb.Models.Breed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BreedId");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("AdoteAquiAppWeb.Models.Animal", b =>
                {
                    b.HasOne("AdoteAquiAppWeb.Models.Breed", null)
                        .WithMany("Animals")
                        .HasForeignKey("BreedId");
                });

            modelBuilder.Entity("AdoteAquiAppWeb.Models.Breed", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
